# Image Caddy avec le plugin OVH pour le challenge DNS-01
FROM caddy:2-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/ovh

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
